resolver = "2"

[workspace]
members = [
    "default-plugins/hello-world"
]

[workspace.dependencies]
anyhow = "1.0.97"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.44.1"
